server {
    listen 80;
    
    # Lokasi root direktori file statis hasil build Vite
    root /usr/share/nginx/html;
    
    # File index default
    index index.html;

    # Mengaktifkan kompresi gzip untuk performa lebih cepat
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Konfigurasi routing utama
    location / {
        # Mencoba mencari file sesuai URL, jika tidak ada arahkan ke index.html (untuk SPA React-Router)
        try_files $uri $uri/ /index.html;
    }
    
    # Caching untuk asset statis
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
